/**
 * VoicePad Official Legal Documents: Terms of Service & Privacy Policy
 * Compliant with App Store Guidelines, Google Play Developer Policies,
 * GDPR, CCPA/CPRA, and audio wiretapping / consent regulations.
 */

export const LEGAL_LAST_UPDATED = 'September 14, 2026';

export interface LegalSection {
  id: string;
  title: string;
  content: string;
}

export const TERMS_OF_SERVICE: {
  title: string;
  lastUpdated: string;
  sections: LegalSection[];
} = {
  title: 'Terms of Service',
  lastUpdated: LEGAL_LAST_UPDATED,
  sections: [
    {
      id: 'acceptance',
      title: '1. Acceptance of Terms',
      content: `By downloading, accessing, or using VoicePad ("Application", "Service", "we", "us", or "our"), you ("User", "you") agree to be legally bound by these Terms of Service. If you do not agree to these terms, do not download, access, or use the Application. We reserve the right to modify these terms at any time; continued use of the Application constitutes your binding acceptance of any modifications.`,
    },
    {
      id: 'eligibility',
      title: '2. Eligibility & Account Responsibilities',
      content: `You must be at least 13 years of age (or 16 years of age in the European Economic Area) to use VoicePad. If you are using the Application on behalf of an organization or legal entity, you represent and warrant that you have full legal authority to bind that entity to these Terms. You are solely responsible for maintaining the confidentiality of your account credentials, passwords, and local security pins.`,
    },
    {
      id: 'recording-consent',
      title: '3. Audio Recording & Multi-Party Consent Laws',
      content: `IMPORTANT LEGAL NOTICE: Audio recording laws vary substantially across local, state, federal, and international jurisdictions. Some jurisdictions require only one party's consent to record a conversation ("one-party consent"), while others mandate that all participants expressly consent prior to recording ("two-party" or "all-party consent").

By using VoicePad's recording features:
• You represent, warrant, and covenant that you have verified applicable laws in your jurisdiction before initiating any audio recording.
• You represent that you have obtained all necessary prior permissions, authorizations, and consents from every individual whose voice or likeness is captured.
• You agree that VoicePad, its creators, affiliates, and service providers bear zero liability for any unlawful, unconsented, or covert audio recordings made by you.`,
    },
    {
      id: 'ai-disclaimer',
      title: '4. AI Transcription & Summary Disclaimer',
      content: `VoicePad incorporates artificial intelligence and automated speech-to-text algorithms (including Whisper speech recognition and large language model summarization). 

You acknowledge and agree that:
• Speech-to-text transcription and natural language summaries are probabilistic outputs generated by machine learning models and may contain inaccuracies, omissions, errors, or hallucinations.
• VoicePad makes no warranties regarding the accuracy, completeness, or reliability of any transcript or summary.
• The Services are NOT intended for use as certified court reporting, medical transcription, legal record-keeping, emergency response documentation, or life-critical applications. Do not rely on AI outputs without independent verification.`,
    },
    {
      id: 'ip-ownership',
      title: '5. Intellectual Property & User Ownership',
      content: `You retain 100% ownership, title, and intellectual property rights in and to your original audio recordings, personal notes, transcripts, and scanned imagery ("User Content"). 

VoicePad does NOT claim ownership of your User Content. We do not sell, rent, license, or use your private voice recordings or notes to train public foundation artificial intelligence models.

You grant VoicePad a strictly limited, non-exclusive license to transmit, store, and process your User Content solely to the extent necessary to deliver the features requested by you (such as syncing to your private cloud storage and routing audio to the transcription proxy).`,
    },
    {
      id: 'prohibited-use',
      title: '6. Prohibited Activities',
      content: `You agree not to engage in any of the following prohibited activities:
• Recording or capturing individuals in confidential, private, or medical settings without explicit authorization.
• Uploading or transcribing material that is defamatory, harassing, sexually explicit, abusive, or infringing on intellectual property.
• Circumventing rate limits, reverse engineering, decompiling, or attempting to discover the server-side API keys or source code of our transcription infrastructure.
• Using the service for automated bulk spamming, denial-of-service, or unauthorized commercial resale of proxy endpoints.`,
    },
    {
      id: 'liability',
      title: '7. Disclaimer of Warranties & Limitation of Liability',
      content: `VOICEPAD IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS, WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, OR NON-INFRINGEMENT.

TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL VOICEPAD, ITS DEVELOPERS, OR AFFILIATES BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING DATA LOSS, LOST PROFITS, DEVICE CORRUPTION, OR BUSINESS INTERRUPTION ARISING OUT OF OR IN CONNECTION WITH YOUR USE OR INABILITY TO USE THE SERVICE.`,
    },
    {
      id: 'termination',
      title: '8. Account Termination & Data Deletion',
      content: `You may terminate your account at any time via the Profile screen by selecting "Delete Account & Data". Upon confirmation, your cloud records and private storage files are purged. We reserve the right to suspend or terminate accounts that repeatedly violate these Terms or abuse the transcription infrastructure.`,
    },
    {
      id: 'contact',
      title: '9. Contact & Inquiries',
      content: `For any questions, legal notices, or feedback regarding these Terms of Service, please contact the development team through the official repository or support channel at support@voicepad.app.`,
    },
  ],
};

export const PRIVACY_POLICY: {
  title: string;
  lastUpdated: string;
  sections: LegalSection[];
} = {
  title: 'Privacy Policy',
  lastUpdated: LEGAL_LAST_UPDATED,
  sections: [
    {
      id: 'overview',
      title: '1. Commitment to Privacy',
      content: `VoicePad is built on a "local-first" privacy model. Your privacy is fundamental to our design. This Privacy Policy details the types of information collected by VoicePad, how that information is processed, stored, and protected, and your rights under global privacy frameworks including GDPR, CCPA/CPRA, and Apple App Store privacy standards.`,
    },
    {
      id: 'data-collected',
      title: '2. Information We Collect & How We Collect It',
      content: `We collect information strictly necessary to provide high-fidelity voice note capturing:

A. Information You Provide:
• Account Information: Email address, encrypted password hash, and optional display name when creating a cloud sync account.
• Audio Recordings: Voice recordings made via microphone or uploaded audio files.
• Scanned Images: Photographs taken with your camera or chosen from your library for text extraction.
• Notes & Transcripts: Text notes, edit history, and categories you organize.

B. Automatically Collected Technical Data:
• Client diagnostics: App version, operating system, crash diagnostics, and network response latency to ensure server stability.`,
    },
    {
      id: 'local-first',
      title: '3. Local-First Architecture',
      content: `VoicePad operates completely offline by default. All notes, recordings, and edits are stored locally on your device using encrypted sandbox storage. If you choose not to create a cloud account, no notes or audio recordings ever leave your device, except when you explicitly initiate an AI transcription or summary request.`,
    },
    {
      id: 'ai-processing',
      title: '4. AI Transcription & Image Processing (Subprocessors)',
      content: `When you request audio transcription, photo-to-text extraction, or AI summarization:
• Your audio file or image payload is transmitted over an encrypted TLS/HTTPS connection directly to our secure proxy server.
• Audio is passed to Whisper models hosted on enterprise infrastructure (Groq Cloud) for transcription.
• Text transcripts are passed to Llama models on Groq Cloud to produce summaries.
• Our enterprise processing agreements with infrastructure providers specify that user audio and prompts are processed ephemerally in volatile memory and are NOT retained or used to train public models.`,
    },
    {
      id: 'cloud-storage',
      title: '5. Cloud Backup & Storage Security',
      content: `If you sign in with a Supabase cloud account:
• Your database records are stored in PostgreSQL with Row Level Security (RLS). You can only access records matching your verified user ID.
• Audio files are stored in a private cloud storage bucket. Downloads require short-lived, cryptographically signed URLs that expire after 50 minutes.
• We do NOT sell, monetize, or broker your personal data to advertisers or third-party data aggregators.`,
    },
    {
      id: 'retention-erasure',
      title: '6. Data Retention & Right to Erasure (GDPR / CCPA)',
      content: `You have full sovereignty over your data:
• Export: You can copy, share, or export your notes and transcripts at any time.
• Erasure: Deleting a note marks it for immediate removal across local and cloud storage.
• Account Deletion: In accordance with Apple Guideline 5.1.1(v) and GDPR Article 17, selecting "Delete Account & Data" in Settings permanently removes your user record, authentication credentials, database rows, and cloud storage files.`,
    },
    {
      id: 'permissions',
      title: '7. Device Permissions Explained',
      content: `VoicePad requests the following permissions exclusively for their stated purposes:
• Microphone (RECORD_AUDIO): Required to record voice notes and speeches.
• Camera: Required when you opt to take a photograph of documents or whiteboards in the Scan tab.
• Photo Library: Required to select an existing photograph for text extraction.
• Document Picker / Storage: Required when you select an existing audio file from your device for transcription.`,
    },
    {
      id: 'children',
      title: '8. Children\'s Online Privacy Protection',
      content: `VoicePad does not knowingly collect or solicit personal identifiable information from children under the age of 13. If we discover that a child under 13 has provided personal information, we will immediately delete such data from our servers.`,
    },
    {
      id: 'contact',
      title: '9. Contact Data Protection Officer',
      content: `If you have questions regarding this Privacy Policy, your rights under GDPR/CCPA, or wish to submit a data subject request, please reach out to privacy@voicepad.app.`,
    },
  ],
};
